Update for Tiny Cloud 3.0.0

diff --git a/scripts/setup-tiny b/scripts/setup-tiny
--- a/scripts/setup-tiny
+++ b/scripts/setup-tiny
@@ -22,4 +22,13 @@ else
 
     sed -i.bak -Ee "s/^#?CLOUD_USER=.*/CLOUD_USER=$IMAGE_LOGIN/" "$TC_CONF"
     rm "$TC_CONF.bak"
+
+    # tiny-cloud >= 3.0.0 sets up init scripts with /sbin/tiny-cloud --setup
+    if [ -f "$TARGET/sbin/tiny-cloud" ]; then
+        chroot "$TARGET" /sbin/tiny-cloud --setup
+    elif [ "$VERSION" = "3.18" ]; then
+        # 3.18 has tiny-cloud 3.0.0, and we didn't find what we expected
+        echo "Error: /sbin/tiny-cloud not found" >&2
+        exit 1
+    fi
 fi
